// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB39VH8OGOw8QbPxi-0EVRpYEH_7iw6Z9U',
    appId: '1:136415840079:web:459c235343dcfd2ac6273a',
    messagingSenderId: '136415840079',
    projectId: 'akhiro-spolangui',
    authDomain: 'akhiro-spolangui.firebaseapp.com',
    storageBucket: 'akhiro-spolangui.firebasestorage.app',
    measurementId: 'G-FBH3LX8ZD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhBcM5aSAfHS0YHS_L6Ay78H8N6E3h7_Y',
    appId: '1:136415840079:android:b5f78bc1154efd80c6273a',
    messagingSenderId: '136415840079',
    projectId: 'akhiro-spolangui',
    storageBucket: 'akhiro-spolangui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RQ7dB_aTDKoRxac2wrhPMiuf-4uWBrc',
    appId: '1:136415840079:ios:c9e0cb2690dc4f6dc6273a',
    messagingSenderId: '136415840079',
    projectId: 'akhiro-spolangui',
    storageBucket: 'akhiro-spolangui.firebasestorage.app',
    iosBundleId: 'com.example.akhiroCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RQ7dB_aTDKoRxac2wrhPMiuf-4uWBrc',
    appId: '1:136415840079:ios:c9e0cb2690dc4f6dc6273a',
    messagingSenderId: '136415840079',
    projectId: 'akhiro-spolangui',
    storageBucket: 'akhiro-spolangui.firebasestorage.app',
    iosBundleId: 'com.example.akhiroCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB39VH8OGOw8QbPxi-0EVRpYEH_7iw6Z9U',
    appId: '1:136415840079:web:2acb106e726a4a35c6273a',
    messagingSenderId: '136415840079',
    projectId: 'akhiro-spolangui',
    authDomain: 'akhiro-spolangui.firebaseapp.com',
    storageBucket: 'akhiro-spolangui.firebasestorage.app',
    measurementId: 'G-SQBGMXYCG3',
  );

}